### ISSUE TITLE
Python - C interfacing

### ISSUE THREAD

**Issue by isacpaulsson** [mosmar99/ChessProjectClass#19]
We need a way of interfacing our python GUI with the Chess engine written in C.

## Basic needed functionality
* Retrieve current board state for display in python GUI.
* Retrieve list of performed moves for display in python GUI.
* Ability to propose a move to the Chess engine from player input.

## To-do
- [ ] Complete To-do list...
- [x] Choose a suitable approach for our purpose.
- [x] Write test implementation for retrieving current board state.
- [x] Implement basic functionality.

## Python - C documentation
Python C-API [Documentation](https://docs.python.org/3/c-api/intro.html).

Python ctypes [Documentation](https://docs.python.org/3/library/ctypes.html).
