### ISSUE TITLE
Lecture 11 — Guest Lecture by Husqvarna: Checklist

### ISSUE THREAD

**Issue by mosmar99** [mosmar99/ChessProjectClass#67]
Carry on with your project implementation using the techniques from this and previous lectures.

- [x] create an issue titled "Lecture 11 checklist" to track these checklist items
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work. #64 
- [x] set your final project goals as issues, link them from the "Lecture 11 checklist" https://github.com/mosmar99/ChessProjectClass/issues/67#issuecomment-1451577599
